---

name: Push to release branch

on:
  release:
    types:
      - published
      - edited
  workflow_run:
    workflows: [Make a Release]
    types: [completed]
    branches: [main]

jobs:

  release-branch:
    uses: VinLudens/lilypond-reusable-workflows/.github/workflows/release-branch.yml@main
    permissions:
      contents: write
    with:
      MAIN_FILE: ${{ vars.MAIN_FILE }}
      RELEASE_BRANCH: release-assets

