---

name: Push to release branch

env:
  RELEASE_BRANCH: release-assets

on:
  release:
    types:
      - published
      - edited
  workflow_run:
    workflows: [Build Lilypond Project]
    types: [completed]

jobs:

  create-branch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: peterjgrainger/action-create-branch@v2.2.0
        id: create-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.RELEASE_BRANCH }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_BRANCH }}
      - name: Remove all files to avoid unwanted files being present
        run: find . -mindepth 1 -maxdepth 1 -not -path ./.git -exec rm -rvf {} +
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ env.RELEASE_BRANCH }}
          create_branch: true


  push-release:
    runs-on: ubuntu-latest
    needs: create-branch
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_BRANCH }}
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: latest
          file: ${{ vars.MAIN_FILE }}.pdf
      - uses: dsaltares/fetch-gh-release-asset@master
        continue-on-error: true
        with:
          version: latest
          file: ${{ vars.MAIN_FILE }}.midi
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: always()
        with:
          branch: ${{ env.RELEASE_BRANCH }}
          create_branch: true

